live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "MonaspiceAr Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceAr Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MonaspiceAr Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceAr Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
